import { test } from 'node:test';
import assert from 'node:assert/strict';
// @ts-expect-error Plain ESM research contract is validated at runtime.
import { checkDraft,fetchSource,validateSourceUrl,canonicalSteamUrl,sourceDigest,sameStory } from '../scripts/research-lib.mjs';
const sources=[{id:'s',platform:'Steam',title:'Update 0.18.0.0',text:'The update adds new equipment controls.',url:'https://store.steampowered.com/news/app/739630'},{id:'k',platform:'Kinetic',title:'Update 0.18.0.0',text:'The update adds new equipment controls.',url:'https://www.kineticgames.co.uk/news'}];
const draft=()=>({title:'Equipment controls are changing',summary:'The developer has announced changes to equipment controls.',version:'0.18.0.0',claims:[{text:'The update includes new equipment controls.',sourceIds:['s','k'],supportingQuotes:[{sourceId:'s',quote:'adds new equipment controls'},{sourceId:'k',quote:'adds new equipment controls'}]}],playerImpact:'Review the bindings before your next contract.',uncertainties:[]});
test('research requires known sources and exact evidence excerpts',()=>{assert.ok(checkDraft(draft(),sources));const invented=draft();invented.claims[0].supportingQuotes[0].quote='The ghost is now completely invisible';assert.throws(()=>checkDraft(invented,sources));const missing=draft();missing.claims[0].sourceIds.push('invented');assert.throws(()=>checkDraft(missing,sources));});
test('multiple posts from one platform do not satisfy cross-platform coverage',()=>{assert.throws(()=>checkDraft(draft(),sources.map(s=>({...s,platform:'Steam'}))));});
test('research refuses private hosts, credentials and off-list redirects',async()=>{for(const url of ['http://localhost/','https://127.0.0.1/','https://evil.example/','https://user:pass@www.kineticgames.co.uk/news'])assert.throws(()=>validateSourceUrl(url));await assert.rejects(()=>fetchSource('https://www.kineticgames.co.uk/news',{fetchImpl:async()=>new Response(null,{status:302,headers:{location:'http://127.0.0.1/private'}})}));});
test('source digest changes after corrections and is order independent',()=>{assert.equal(sourceDigest(sources),sourceDigest([...sources].reverse()));assert.notEqual(sourceDigest(sources),sourceDigest([{...sources[0],text:'Corrected'},sources[1]]));});
test('an unrelated title does not become the same story',()=>{assert.equal(sameStory({title:'Summer character wardrobe'},{title:'Winter hunting challenge',text:'Different event'}),false);});
test('Steam CDN article paths are canonicalised without allowing arbitrary CDN content',()=>{assert.equal(canonicalSteamUrl('https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/12345'),'https://store.steampowered.com/news/externalpost/steam_community_announcements/12345');for(const url of ['https://steamstore-a.akamaihd.net/unrelated','https://evil.example/news/externalpost/steam_community_announcements/12345','http://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/12345'])assert.throws(()=>canonicalSteamUrl(url));});
test('published reports enforce the 180-word summary budget',()=>{const long=draft();long.claims=Array.from({length:5},()=>({...long.claims[0],text:'supported '.repeat(50).trim()}));assert.throws(()=>checkDraft(long,sources));});
