import { useEffect,useState } from 'react';
import { z } from 'zod';
import { Link,useHub } from './context';
import { readValue } from './storage';
import { Empty,Notice,PageHeading } from './ui';
const GuestSchema=z.object({token:z.string(),id:z.string(),nickname:z.string()});
const AppealSchema=z.object({id:z.string(),reason:z.string(),status:z.enum(['open','resolved']),reply:z.string(),createdAt:z.string(),reviewedAt:z.string().nullable()});
const ResponseSchema=z.object({appeals:z.array(AppealSchema),timeoutUntil:z.number()});
type Appeal=z.infer<typeof AppealSchema>;
export function Appeals(){
 const {api,notice}=useHub();const [guest]=useState(()=>readValue('guest',GuestSchema.nullable(),null)),[appeals,setAppeals]=useState<Appeal[]>([]),[timeout,setTimeoutUntil]=useState(0),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 async function request(method='GET',signal?:AbortSignal){if(!guest||!api)return;const response=await fetch(api+'/appeals',{method,signal:signal??AbortSignal.timeout(12000),headers:{Authorization:'Bearer '+guest.token,...(method==='POST'?{'Content-Type':'application/json'}:{})},...(method==='POST'?{body:JSON.stringify({reason})}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error??'Appeal request failed.');return data;}
 async function refresh(){setBusy(true);setError('');try{const data=ResponseSchema.parse(await request());setAppeals(data.appeals);setTimeoutUntil(data.timeoutUntil);setLoaded(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!api||!guest)return;const controller=new AbortController();let alive=true;const timer=setTimeout(()=>controller.abort(),12000);request('GET',controller.signal).then(data=>{if(!alive)return;const result=ResponseSchema.parse(data);setAppeals(result.appeals);setTimeoutUntil(result.timeoutUntil);setLoaded(true);}).catch(e=>{if(alive)setError(e.name==='AbortError'?'The service did not respond in time. Try refreshing.':e.message);});return()=>{alive=false;controller.abort();clearTimeout(timer);};},[api,guest]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await request('POST');setReason('');notice('Appeal submitted privately to the owner.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><PageHeading eyebrow="COMMUNITY / A FAIR HEARING" title="Ask for another look." description="A timeout should not prevent you from explaining what happened."/>{!api?<Empty title="The moderation service is not connected">Appeals will be available alongside the hosted global chat.</Empty>:!guest?<section className="panel prose"><h2>No guest session on this browser</h2><p>Use the browser where the timeout occurred. Appeals are tied to its guest token, not your PC hardware or an email address.</p><Link className="button" to="chat">Open global chat</Link></section>:<div className="two-columns"><section className="panel prose"><h2>Your appeal</h2><p>Signed in as {guest.nickname}. {timeout>Date.now()?'Timeout ends '+new Date(timeout).toLocaleString()+'.':'No current timeout is recorded in the last loaded status.'}</p><Notice>Only you and the owner can read your appeal. Keep the explanation factual and do not include private personal information. Human review is not instant or guaranteed.</Notice>{error&&<Notice>{error}</Notice>}<button className="button" disabled={busy} onClick={()=>void refresh()}>Refresh status</button>{loaded&&!appeals.some(a=>a.status==='open')&&<form className="appeal-form" onSubmit={submit}><label>What should the owner reconsider?<textarea required minLength={10} maxLength={1000} rows={6} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="small muted">One open appeal at a time. Maximum one submission per guest per day.</p><button className="button primary" disabled={busy||reason.trim().length<10}>Send private appeal</button></form>}</section><section className="panel prose"><h2>Your recent appeals</h2>{loaded&&!appeals.length&&<p className="muted">You have not submitted an appeal.</p>}{appeals.map(a=><article className="appeal-entry" key={a.id}><span className="tag">{a.status}</span><p className="small muted">{new Date(a.createdAt).toLocaleString()}</p><p className="case-notes">{a.reason}</p>{a.reply&&<blockquote><strong>Owner response</strong><p className="case-notes">{a.reply}</p></blockquote>}</article>)}<p className="small muted">Appeals are retained for up to 90 days. Access requires the original guest token, which expires after 30 days. Clearing browser data can remove your access.</p></section></div>}</>;
}
type OwnerAppeal=Appeal&{guestId:string;nickname:string|null;timeoutUntil:number|null};
export function ModerationAppeals({appeals,action}:{appeals:OwnerAppeal[];action:(body:unknown)=>Promise<void>}){
 const [drafts,setDrafts]=useState<Record<string,string>>({}),[pending,setPending]=useState('');
 async function resolve(a:OwnerAppeal,outcome:'lift'|'uphold'){setPending(a.id);try{await action({action:'appeal-resolve',appealId:a.id,reply:drafts[a.id]?.trim(),outcome});}finally{setPending('');}}
 return <section className="panel admin-section"><h2>Moderation appeals</h2>{!appeals.length&&<p className="muted">No appeals submitted.</p>}{appeals.map(a=><article className="admin-row" key={a.id}><strong>{a.nickname??'Expired guest'} / {a.status}</strong><p className="case-notes">{a.reason}</p>{a.status==='open'?<><label>Reply to this guest<textarea rows={3} maxLength={1000} aria-label={'Appeal reply for '+(a.nickname??a.guestId)} value={drafts[a.id]??''} onChange={e=>setDrafts({...drafts,[a.id]:e.target.value})}/></label><div className="button-row"><button className="button" disabled={!!pending||(drafts[a.id]?.trim().length??0)<3} onClick={()=>void resolve(a,'lift')}>Reply & lift timeout</button><button className="button" disabled={!!pending||(drafts[a.id]?.trim().length??0)<3} onClick={()=>void resolve(a,'uphold')}>Reply & keep decision</button></div></>:<blockquote className="case-notes">{a.reply}</blockquote>}</article>)}</section>;
}
