import {useLayoutEffect,useRef,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Compass,FileText,Ghost,List,Map,NotebookPen,Timer} from 'lucide-react';
import {Link,useHub} from './context';
import {chapters} from './navigation';
import {EVIDENCE} from './model';
import {MAPS} from './content';
import {PageHeading} from './ui';

const bookmarks=[{to:'evidence',name:'Evidence',icon:BookOpen},{to:'detective',name:'Detective',icon:Ghost},{to:'journal',name:'Notes',icon:NotebookPen},{to:'ghosts',name:'Ghosts',icon:Compass},{to:'maps',name:'Maps',icon:Map},{to:'tools',name:'Tools',icon:Timer}];
export function Casebook({path,children}:{path:string;children:ReactNode}){
  const {session,candidates,effects}=useHub();const section=path.split(/[/?]/)[0];const index=chapters.findIndex(c=>c[0]===section),leaf=useRef<HTMLDivElement>(null),previous=useRef(index),motion=useRef<Animation>();
  useLayoutEffect(()=>{motion.current?.cancel();if(effects&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&previous.current!==index){motion.current=leaf.current?.animate([{transform:`translateX(${index>=previous.current?8:-8}px)`,opacity:.35},{transform:'translateX(0)',opacity:0}],{duration:160,easing:'ease-out'});}previous.current=index;return()=>motion.current?.cancel();},[path,effects,index]);
  return <section className="casebook" aria-label="Casebook Preview"><header className="casebook-masthead"><div><span className="eyebrow">GHOST HUB / FIELD EDITION</span><strong>The investigator’s casebook</strong></div><span className="tag">PREVIEW</span><Link to={path==='contents'||path==='overview'?'':path} presentation="classic" className="text-link">Classic view<ArrowRight size={16}/></Link></header>
  <nav className="book-bookmarks" aria-label="Book bookmarks"><Link to="contents" className={'book-tab '+(section==='contents'?'active':'')} aria-current={section==='contents'?'page':undefined}><List size={17}/>Contents</Link>{bookmarks.map(({to,name,icon:Icon})=><Link key={to} to={to} className={'book-tab '+(section===to?'active':'')} aria-current={section===to?'page':undefined}><Icon size={17}/>{name}</Link>)}</nav>
  <div className="book-cover"><div className="book-binding" aria-hidden="true"/><div className="book-paper"><div ref={leaf} className="book-turn-edge" aria-hidden="true"/><div className="book-case-strip"><span>{MAPS.find(m=>m.id===session.map)?.name??session.map}</span><div>{EVIDENCE.filter(e=>session.evidence[e.id]==='found').map(e=><span key={e.id} className="book-evidence">{e.short}</span>)}</div><span>{candidates.filter(c=>!c.eliminated).length} possibilities</span></div><div className="book-leaf">{children}</div><footer className="book-pagination">{index>0?<Link to={chapters[index-1][0]} className="button"><ArrowLeft size={16}/>{chapters[index-1][1]}</Link>:<Link to="contents" className="button"><List size={16}/>Contents</Link>}<span>{index>=0?`${String(index+1).padStart(2,'0')} / ${chapters.length}`:'FIELD REFERENCE'}</span>{index>=0&&index<chapters.length-1?<Link className="button" to={chapters[index+1][0]}>{chapters[index+1][1]}<ArrowRight size={16}/></Link>:<Link to="evidence" className="button">Evidence<ArrowRight size={16}/></Link>}</footer></div></div></section>;
}
const groups=[{title:'Your investigation',items:[['evidence','Evidence','Record results and narrow the case.'],['detective','Detective','Talk through what you noticed.'],['journal','Notes & journal','Keep your findings and saved cases.'],['tools','Field tools','Timers, rhythm and your checklist.'],['voice','Voice console','Review a spoken or typed command.']]},{title:'The reference shelves',items:[['ghosts','Ghost encyclopaedia','Compare the remaining possibilities.'],['maps','Map atlas','Keep your plans and floor notes.'],['equipment','Equipment','Understand your tools and results.'],['guides','Guides & mechanics','Read the conditions behind a clue.'],['cursed','Cursed possessions','Understand an item before using it.'],['bugs','Known bugs','Separate an issue from a mechanic.']]},{title:'Beyond the case',items:[['','Overview','Return to Ghost Hub headquarters.'],['updates','News & reports','Browse the reviewed archive.'],['community','Community','Resources and community information.'],['chat','Global chat','Connected conversation when available.'],['share','Share a case','Create a reviewed case snapshot.'],['search','Search the book','Find a topic across the reference.'],['submit','Submit a finding','Share a correction through the service.'],['appeals','Moderation appeals','Review your service appeal.'],['settings','Settings','Appearance, data and connections.'],['about','About & sources','Sources, privacy and project details.'],['admin','Owner moderation','Sign in to the existing owner tools.']]}];
export function Contents(){return <><PageHeading eyebrow="A PLACE FOR EVERY CLUE" title="Contents" description="Pick up a thread. Your place in each chapter is kept for you."/><div className="book-contents">{groups.map(group=><section key={group.title}><h2>{group.title}</h2>{group.items.map(([to,name,description])=><Link to={to} className="contents-entry" key={to}><FileText size={18}/><span><strong>{name}</strong><small>{description}</small></span><ArrowRight size={16}/></Link>)}</section>)}</div></>;}
