import { EXTRA_EQUIPMENT } from './extraEquipment';
export const MAPS = [
  {id:'prison-restricted',name:'Prison Restricted',type:'Small',setting:'Restricted prison area',floors:['Accessible area'],tip:'Introduced in the August 2026 quality-of-life release. Inspect the actual accessible rooms before placing markers; older full-map routes may cross blockades.',wiki:'Prison'},
  {id:'brownstone-restricted',name:'Brownstone High School Restricted',type:'Medium',setting:'Restricted school area',floors:['Accessible area'],tip:'Check which corridors are open this contract. September fixes address inaccessible bone and fuse-box placement issues on restricted maps.',wiki:'Brownstone_High_School'},
  {id:'point-hope-restricted',name:'Point Hope Restricted',type:'Small',setting:'Restricted lighthouse area',floors:['Accessible area'],tip:'Use the in-game restricted layout as the authority. Mark only accessible floors and avoid relying on screenshots from earlier patches.',wiki:'Point_Hope'},
  {id:'tanglewood',name:'6 Tanglewood Drive',type:'Small',setting:'Suburban home',floors:['Ground floor','Basement'],tip:'A compact contract for learning an evidence routine. Identify hiding options before collecting equipment.',wiki:'6_Tanglewood_Drive'},
  {id:'edgefield',name:'42 Edgefield Road',type:'Small',setting:'Three-storey home',floors:['Ground floor','First floor','Basement'],tip:'Separate sound from above or below before assuming the ghost is in the room beside you.',wiki:'42_Edgefield_Road'},
  {id:'ridgeview',name:'10 Ridgeview Court',type:'Small',setting:'Family home',floors:['Ground floor','First floor','Basement'],tip:'Mark the ghost room and the route back to your equipment; check hiding availability each contract.',wiki:'10_Ridgeview_Court'},
  {id:'willow',name:'13 Willow Street',type:'Small',setting:'Reworked residence',floors:['Ground floor','Basement'],tip:'The July 2026 rework means older diagrams can be outdated. Open the current reference before planning a route.',wiki:'13_Willow_Street'},
  {id:'grafton',name:'Grafton Farmhouse',type:'Small',setting:'Rural farmhouse',floors:['Ground floor','First floor'],tip:'Use current post-rework references. Reconfirm room boundaries and escape routes in the contract.',wiki:'Grafton_Farmhouse'},
  {id:'bleasdale',name:'Bleasdale Farmhouse',type:'Small',setting:'Rural farmhouse',floors:['Ground floor','First floor','Attic'],tip:'A vertical search needs clear team callouts. Label the floor as well as the room in your notes.',wiki:'Bleasdale_Farmhouse'},
  {id:'woodwind',name:'Camp Woodwind',type:'Small',setting:'Open-air campsite',floors:['Camp'],tip:'Outdoor sound and visual clutter can mislead. Confirm an observation with the relevant equipment.',wiki:'Camp_Woodwind'},
  {id:'maple',name:'Maple Lodge Campsite',type:'Medium',setting:'Lakeside campsite',floors:['Camp','Cabin upper floor'],tip:'Divide the search into areas and keep the return route to the truck clear.',wiki:'Maple_Lodge_Campsite'},
  {id:'prison',name:'Prison',type:'Medium',setting:'Correctional facility',floors:['Ground floor','First floor'],tip:'Use named blocks in callouts and establish where evidence equipment will be staged.',wiki:'Prison'},
  {id:'brownstone',name:'Brownstone High School',type:'Large',setting:'Abandoned school',floors:['Ground floor','First floor'],tip:'Search in teams by floor or corridor. Record the location of sounds before moving all equipment.',wiki:'Brownstone_High_School'},
  {id:'sunny',name:'Sunny Meadows',type:'Large',setting:'Mental institution',floors:['Ground floor','Basement'],tip:'Plan around wing access and long travel times. Check the current map reference for room detail.',wiki:'Sunny_Meadows_Mental_Institution'},
  {id:'sunny-restricted',name:'Sunny Meadows Restricted',type:'Small',setting:'Restricted wing',floors:['Available wing'],tip:'The accessible area depends on the contract. Mark only the wing you can actually enter.',wiki:'Sunny_Meadows_Mental_Institution_-_Restricted'},
  {id:'point-hope',name:'Point Hope',type:'Small',setting:'Lighthouse',floors:['Ground floor','Floors 2-4','Floors 5-7','Floors 8-10'],tip:'Vertical distance matters. Label every observation by floor instead of relying on footsteps alone.',wiki:'Point_Hope'},
  {id:'nells',name:"Nell's Diner",type:'Small',setting:'Roadside diner',floors:['Ground floor'],tip:'Scout the location before committing to a test. Confirm room names using the in-game truck map.',wiki:"Nell%27s_Diner"}
];
export type MapEntry=typeof MAPS[number];
export const EQUIPMENT = [
  {id:'emf-reader',name:'EMF Reader',category:'Evidence',icon:'activity',summary:'Read interactions. Find the signal that matters.',steps:['Scan the location of a recent interaction.','Confirm Level 5 on the actual device.','Repeat on fresh interactions if no evidence appears.'],caution:'Hunt and event interference is not a reliable evidence reading.',tiers:['Analogue needle; read it carefully.','LED levels and audio feedback.','Directional display for locating readings.'],wiki:'EMF_Reader',evidence:'emf'},
  {id:'spirit-box',name:'Spirit Box',category:'Evidence',icon:'radio',summary:'Ask a question. Listen for an actual reply.',steps:['Confirm the room lights and response conditions.','Stay within your equipment tier range.','Use the device feedback to confirm that the question registered.'],caution:'A failed response is not a confirmed absence of Spirit Box evidence.',tiers:['Shorter working range.','Improved range and response performance.','Wider range and clearer response feedback.'],wiki:'Spirit_Box',evidence:'box'},
  {id:'uv-light',name:'UV Light',category:'Evidence',icon:'fingerprint',summary:'Reveal the traces an interaction leaves behind.',steps:['Check a recently touched surface promptly.','Distinguish a disturbed salt pile from UV footprints.','Recheck other valid interactions if no print appears.'],caution:'Print chance, disappearance, hidden evidence and ghost mechanics affect negative tests.',tiers:['Narrow ultraviolet flashlight.','Non-electronic ultraviolet glowstick.','Wide ultraviolet flashlight.'],wiki:'UV_Light',evidence:'uv'},
  {id:'thermometer',name:'Thermometer',category:'Evidence',icon:'thermometer',summary:'Measure temperature. Breath is only a lead.',steps:['Take readings in the suspected room.','Allow for temperature changes and measurement time.','Confirm a sub-zero reading before marking freezing.'],caution:'A cold room is useful for searching but is not automatically freezing evidence.',tiers:['Analogue reading.','Digital temperature checks.','Faster digital checks.'],wiki:'Thermometer',evidence:'freezing'},
  {id:'dots-projector',name:'D.O.T.S. Projector',category:'Evidence',icon:'scan',summary:'Watch for a silhouette crossing the light.',steps:['Cover an area the ghost actually moves through.','Watch directly and through a video camera.','For a Goryo test, keep players outside the ghost room.'],caution:'Your breath or another player is not the ghost silhouette.',tiers:['Handheld directional coverage.','Placed coverage.','Wider scanning coverage.'],wiki:'D.O.T.S._Projector',evidence:'dots'},
  {id:'writing-book',name:'Ghost Writing Book',category:'Evidence',icon:'book',summary:'Give the ghost a page to answer on.',steps:['Place the book open in an active area.','Reposition if the ghost changes location.','Check for actual writing instead of assuming a thrown book is conclusive.'],caution:'On reduced evidence a ghost may hide writing. Waiting a long time does not rule it out.',tiers:['Basic interaction area.','Improved interaction coverage.','Largest interaction coverage.'],wiki:'Ghost_Writing_Book',evidence:'writing'},
  {id:'video-camera',name:'Video Camera',category:'Evidence',icon:'camera',summary:'Find orbs and observe from a distance.',steps:['Scan the room in night vision.','Try more than one angle and height.','Watch for D.O.T.S. while your team is outside the room.'],caution:'Check for Mimic orbs even on zero-evidence contracts.',tiers:['Basic recording view.','Improved picture and coverage.','Enhanced viewing performance.'],wiki:'Video_Camera',evidence:'orbs'},
  {id:'incense',name:'Incense',category:'Protection',icon:'flame',summary:'A short window to escape. A longer window to investigate.',steps:['Carry an igniter.','Use incense within the effective range of the ghost.','Start a timer only after a confirmed successful cleanse.'],caution:'Hunt prevention and temporary blindness during a hunt are different effects.',tiers:['Base protection behaviour.','Adds movement effects.','Stronger movement effects; account for them during speed tests.'],wiki:'Incense'},
  {id:'crucifix',name:'Crucifix',category:'Protection',icon:'cross',summary:'Protect the area where a hunt could begin.',steps:['Place it where the ghost is likely to attempt a hunt.','Check coverage and remaining charges.','Log a consumed charge as a prevented attempt.'],caution:'It does not stop an ordinary hunt that has already started.',tiers:['Limited range and one use.','Improved coverage and uses.','Enhanced coverage and special cursed-hunt protection when charged.'],wiki:'Crucifix'},
  {id:'salt',name:'Salt',category:'Tracking',icon:'footprints',summary:'Confirm a path, then check for ultraviolet.',steps:['Place piles along a likely route.','Confirm the ghost crosses the pile.','Inspect footprints separately using UV.'],caution:'Untouched salt is not a Wraith confirmation; Gallu state and Mimic behaviour matter.',tiers:['Basic tracking.','More tracking coverage.','Additional hunt interaction; can affect speed observations.'],wiki:'Salt'},
  {id:'parabolic',name:'Parabolic Microphone',category:'Tracking',icon:'ear',summary:'Listen across larger spaces.',steps:['Scan distinct directions.','Record the location and timing of sounds.','Compare distinctive sounds with a trusted reference.'],caution:'A normal whisper or song is not a Banshee confirmation.',tiers:['Basic directional listening.','Enhanced sound localisation.','Improved directional information.'],wiki:'Parabolic_Microphone'},
  {id:'motion-sensor',name:'Motion Sensor',category:'Tracking',icon:'radar',summary:'Turn an assumed route into an observed crossing.',steps:['Place sensors along the path being tested.','Account for players triggering the sensor.','Pair the crossing with the observation you are checking.'],caution:'A trigger confirms movement in its coverage, not a ghost type.',tiers:['Basic motion detection.','Expanded detection options.','Advanced detection coverage.'],wiki:'Motion_Sensor'},
  ...EXTRA_EQUIPMENT
];
export const GUIDES = [
  {id:'first-contract',title:'Your first contract, without the panic',category:'Getting started',minutes:5,summary:'A practical routine from opening the truck to choosing a ghost.',sections:[['Start with an exit plan','Check the contract difficulty, find accessible hiding options, and agree on room names before starting risky tests.'],['Find activity, then collect evidence','Use interactions and equipment to locate the ghost. Place your passive tools, then work through active checks. Record what actually happened, not what you expected.'],['Make the next test count','Enter confirmed evidence in the Evidence Book. Compare the remaining candidates and choose a test that distinguishes them. You do not need to memorise every ghost at once.']],source:'https://phasmophobia.fandom.com/wiki/Guides/Locating_the_ghost'},
  {id:'missing-evidence',title:'When the last evidence will not show',category:'Evidence',minutes:4,summary:'Separate hidden evidence, poor test conditions, and simple bad luck.',sections:[['Check the contract first','On reduced-evidence settings, some evidence is deliberately unavailable. Set the correct evidence count before filtering.'],['Audit the test','Confirm equipment placement, range, room location, lighting and any relevant player-presence conditions. A long wait does not automatically make a negative result.'],['Use the candidates','Look for a discriminating test among the remaining ghosts. Ghost Hub evaluates possible evidence sets, including forced evidence and Mimic orbs.']],source:'https://phasmophobia.fandom.com/wiki/Evidence'},
  {id:'hunt-or-event',title:'A hunt or just an event?',category:'Survival',minutes:4,summary:'Do not use one flickering light as your entire diagnosis.',sections:[['Use several signals','Equipment interference and manifestations occur in more than one situation. Learn the combination of door behaviour, escape availability and ghost behaviour relevant to your contract.'],['Respond conservatively','Have your escape route and protection ready. Turn off held electronics and avoid broadcasting your location when trying to hide.'],['Log it afterwards','Once safe, record whether the event was a normal hunt, a cursed hunt, or still uncertain. That context changes how useful an early-hunt observation is.']],source:'https://phasmophobia.fandom.com/wiki/Hunt'},
  {id:'mimic',title:'The Mimic exception',category:'Ghost mechanics',minutes:3,summary:'Why an extra orb changes your investigation.',sections:[['Evidence stays its own','The Mimic copies behaviour, not the full evidence combination of the ghost it imitates.'],['Orbs are extra','It produces ghost orbs in addition to the evidence allowed by the difficulty. Check for them even in zero-evidence games.'],['Keep tests connected','A distinctive behaviour can still be an imitation. Combine it with confirmed evidence and watch for changes across the investigation.']],source:'https://phasmophobia.fandom.com/wiki/The_Mimic'},
  {id:'sanity',title:'Sanity is context, not a stopwatch',category:'Mechanics',minutes:4,summary:'Understand why an early hunt needs more than a percentage.',sections:[['Track the team context','Some mechanics depend on team sanity while others have different targeting or conditional rules. Record whether your number is measured or estimated.'],['Look for exceptions','Cursed possessions and special ghost abilities can change when a hunt occurs. Darkness, talking, equipment and player proximity may matter for specific candidates.'],['Avoid false eliminations','Ghost Hub keeps sanity as a session note rather than applying a universal hard cutoff. Add the circumstances to the Detective for a more useful comparison.']],source:'https://phasmophobia.fandom.com/wiki/Sanity'},
  {id:'speed',title:'Listen to the hunt, carefully',category:'Advanced',minutes:5,summary:'Footstep comparisons work best when the conditions match.',sections:[['Control the comparison','Ghost-speed settings, line of sight, temperature, sanity, equipment and distance can affect the result. Compare like with like.'],['Record instead of guessing','The tap tool measures the rhythm you enter. It does not magically know the ghost speed or type.'],['Do not force a dangerous test','Collect evidence and observe naturally where possible. Plan an escape and understand your suspected ghosts before choosing a hunt-based test.']],source:'https://phasmophobia.fandom.com/wiki/Hunt'},
  {id:'cursed-possessions',title:'Cursed possessions: know the trade',category:'Mechanics',minutes:5,summary:'Powerful information comes with consequences.',sections:[['Identify the object','The Ouija Board, Haunted Mirror, Music Box, Summoning Circle, Tarot Cards, Voodoo Doll and Monkey Paw each have their own rules. Read the current object reference before using it.'],['Prepare the team','Explain what you intend to do, check protection, and give teammates time to move. An activation can change the entire contract.'],['Keep your observations separate','A hunt triggered by a cursed possession does not establish a ghost\'s normal sanity threshold. Record it as a cursed event in your notes.']],source:'https://phasmophobia.fandom.com/wiki/Cursed_possession'},
  {id:'good-observation',title:'How to turn a hunch into a useful test',category:'Research',minutes:3,summary:'The best observation includes the conditions around it.',sections:[['Write the exact event','Prefer "the pile changed after a confirmed crossing" to "it likes salt". Include difficulty, equipment tier and whether a hunt was happening.'],['Repeat and compare','Repeat under similar conditions, account for other players, and preserve a clip if possible. Repetition helps, but several reposts of one clip are not independent tests.'],['Share responsibly','Submit a finding with the version and supporting evidence. Community observations are research leads until the mechanism is supported.']],source:'https://tybayn.github.io/phasmo-cheat-sheet/'}
];
export const RESOURCES=[
  {title:'Phasmophobia on Reddit',type:'Discussion',description:'Player questions, unusual contracts and community conversation.',url:'https://www.reddit.com/r/PhasmophobiaGame/'},
  {title:'Phasmophobia Wiki',type:'Reference',description:'Detailed mechanics, equipment references and page histories. Check update dates.',url:'https://phasmophobia.fandom.com/wiki/Main_Page'},
  {title:'Unofficial Cheat Sheet',type:'Tools',description:'Community investigation tools and research by Ty Bayn / Zero-Network.',url:'https://tybayn.github.io/phasmo-cheat-sheet/'},
  {title:'Kinetic Games news',type:'Official',description:'Original developer announcements and patch information.',url:'https://www.kineticgames.co.uk/news'},
  {title:'Steam announcements',type:'Official',description:'Developer posts and released update notes for Phasmophobia.',url:'https://store.steampowered.com/news/app/739630'},
  {title:'Community guides on Steam',type:'Guides',description:'Long-form player guides. Check version coverage and distinguish opinions from tested facts.',url:'https://steamcommunity.com/app/739630/guides/'}
];
