// Practical field notes; exact numeric upgrade values stay in the linked reference.
export const EXTRA_EQUIPMENT=[
 {id:'flashlight',name:'Flashlight',category:'Utility',icon:'scan',summary:'Keep a route readable without confusing illumination with evidence.',steps:['Choose a beam that suits the room and your display.','Remember your route before a hunt begins.','Switch off carried electronic equipment when hiding.'],caution:'A flickering flashlight is not an EMF 5 reading or a ghost identification.',tiers:['Practise a familiar route with the basic beam.','Compare the upgraded coverage before committing to an unfamiliar route.','A brighter beam still does not make a hiding place safe.'],wiki:'Flashlight'},
 {id:'photo-camera',name:'Photo Camera',category:'Media',icon:'camera',summary:'Document a visible subject, then check what the journal actually credited.',steps:['Frame the subject clearly.','Inspect the captured media rather than assuming the shutter means success.','Record evidence separately from media rewards.'],caution:'A rejected or duplicate capture is not proof that the subject or its evidence was absent.',tiers:['Use the basic camera to learn valid subjects.','Check the upgrade card for current capture handling.','Compare current media rewards and handling before upgrading.'],wiki:'Photo_Camera'},
 {id:'head-gear',name:'Head Gear',category:'Utility',icon:'camera',summary:'Hands-free viewing options that change substantially with the tier.',steps:['Agree whether your team needs a live view or personal lighting.','Learn the activation control before entering.','Disable electronic head gear when your hiding plan requires it.'],caution:'Tier III night vision does not reveal Ghost Orbs. Use a video camera for that evidence.',tiers:['Head-mounted camera for a remote view.','Head-mounted flashlight.','Night-vision goggles, not an orb detector.'],wiki:'Head_Gear'},
 {id:'sanity-medication',name:'Sanity Medication',category:'Protection',icon:'cross',summary:'Manage the investigation window instead of guessing how long you have left.',steps:['Read the current difficulty\'s restoration setting.','Coordinate use around average team sanity, not only your own number.','Allow for the selected tier\'s restoration behaviour.'],caution:'Medication is not hunt immunity. Some ghosts and cursed possessions bypass the assumption you are making.',tiers:['A gradual restoration option.','A faster restoration option.','An injection with an additional stamina-related benefit.'],wiki:'Sanity_Medication'},
 {id:'firelight',name:'Firelight',category:'Utility',icon:'flame',summary:'A non-electronic light source and an observation to log carefully.',steps:['Bring an igniter and choose a position you can observe.','Record who lit or extinguished the flame and when.','Separate a flame interaction from the rest of the hunting conditions.'],caution:'An extinguished flame alone does not confirm Onryo. Do not silently turn a casual blowout into a controlled test.',tiers:['Check the basic candle\'s current duration.','Compare its upgraded duration and handling.','Check the highest-tier coverage and durability in the current upgrade card.'],wiki:'Firelight'},
 {id:'igniter',name:'Igniter',category:'Utility',icon:'flame',summary:'Prepare the ignition step before you need incense or a firelight.',steps:['Bring an igniter with the item you intend to light.','Practise the inventory and use controls before an emergency.','Plan around the current tier\'s available uses.'],caution:'Owning incense without a usable igniter is not a complete protection plan.',tiers:['Matches require deliberate use.','A lighter changes the handling.','Review the upgraded lighter\'s current usage limits.'],wiki:'Igniter'},
 {id:'sound-sensor',name:'Sound Sensor',category:'Tracking',icon:'ear',summary:'Listen to covered areas from the truck and use the result to plan a closer check.',steps:['Cover distinct areas instead of stacking identical coverage.','Label each placement for the truck player.','Compare timestamps with teammates\' actions.'],caution:'A sound in the monitored area is a lead, not a ghost-type diagnosis.',tiers:['Learn the basic coverage.','Compare coverage options in the upgrade card.','Use expanded coverage deliberately rather than assuming more sound means better evidence.'],wiki:'Sound_Sensor'},
 {id:'sound-recorder',name:'Sound Recorder',category:'Media',icon:'radio',summary:'Capture paranormal audio for the media journal.',steps:['Prepare the recorder before the sound you intend to document.','Listen to the result and inspect the journal entry.','Label where and when it happened.'],caution:'This records media; it does not replace the Spirit Box evidence test.',tiers:['Capture valid audio before optimising the reward.','Higher media tiers can improve rewards.','Check the current upgrade card for exact reward and handling differences.'],wiki:'Sound_Recorder'},
 {id:'tripod',name:'Tripod',category:'Utility',icon:'radar',summary:'Hold a deliberate video-camera angle while the team works elsewhere.',steps:['Choose a sightline that covers the suspected area.','Check the feed from the truck before leaving the placement.','Move it when the investigation moves rather than trusting an old angle.'],caution:'A mounted camera still needs a useful view. An obstructed feed cannot rule out Orbs or D.O.T.S.',tiers:['A basic camera support.','Compare stability and handling upgrades.','Review the current tier\'s resistance to being moved or thrown.'],wiki:'Tripod'}
];
