import { ArrowRight,ArrowUpRight,BookOpen,Clock,Compass,Ghost,Map,NotebookPen,Search,ShieldCheck,Sparkles,Timer } from 'lucide-react';
import { useState } from 'react';
import { Link,imagePath,route,useHub } from './context';
import { EVIDENCE } from './model';
import { EvidenceTags,Eyebrow,SectionTitle } from './ui';
import { GUIDES,MAPS } from './content';

export default function Home(){
 const {catalog,news,session,candidates}=useHub();const [query,setQuery]=useState('');const active=candidates.filter(c=>!c.eliminated);const found=EVIDENCE.filter(e=>session.evidence[e.id]==='found');
 const dispatch=(e:React.FormEvent)=>{e.preventDefault();if(query.trim())route('detective?q='+encodeURIComponent(query.trim()));};
 const articles=news.reports.filter(r=>r.category!=='Field note').slice(0,2);
 return <><div className="home-intro"><div><Eyebrow>THE PHASMOPHOBIA COMPANION</Eyebrow><h1>Welcome to the hub.</h1></div><span className="reference-stamp"><span className="status-dot"/>Reference snapshot <b>{catalog.reviewedAt}</b></span></div>
 <section className="home-hero"><img src={imagePath} alt="An isolated house in moonlit fog, with a single dim porch light" className="hero-photo" fetchPriority="high"/><div className="hero-vignette"/><div className="hero-mist"/><div className="hero-content"><span className="hero-kicker"><span className="small-cross"/> TRUST THE EVIDENCE. QUESTION EVERYTHING ELSE.</span><h2>EVERY GHOST<br/>LEAVES A <em>TRACE.</em></h2><p>One strange noise. One missing clue.<br/>Let us help you connect the dots.</p><form className="hero-search" onSubmit={dispatch}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What is your ghost doing?" aria-label="Describe your ghost's behaviour"/><button aria-label="Ask the Ghost Detective" type="submit"><ArrowRight size={20}/></button></form><div className="hero-suggestions"><span>TRY</span>{['Avoiding salt','Playing with electricity','Very little activity'].map(s=><button key={s} onClick={()=>route('detective?q='+encodeURIComponent(s))}>{s}<ArrowUpRight size={12}/></button>)}</div></div><div className="hero-caption"><span className="recording-dot"/> FIELD DESK / GHOST HUB <span>01</span></div></section>
 <div className="quick-tools">{[{to:'evidence',icon:BookOpen,title:'Evidence book',sub:'Narrow down your ghost'},{to:'detective',icon:Ghost,title:'Ghost Detective',sub:'Make sense of the unusual'},{to:'maps',icon:Map,title:'Map atlas',sub:'Know your surroundings'},{to:'tools',icon:Timer,title:'Field tools',sub:'Keep your timing sharp'}].map(({to,icon:Icon,title,sub})=><Link to={to} key={to} className="quick-tool"><div className="icon-box"><Icon size={22}/></div><div><h3>{title}</h3><span>{sub}</span></div><ArrowUpRight size={17}/></Link>)}</div>
 <div className="home-columns"><div><SectionTitle title="From the research desk" to="updates" label="All reports"/><div className="report-grid">{articles.map((r,i)=><Link to={'updates/'+r.id} className="report-card" key={r.id}><div className={'report-image crop-'+i}><img src={imagePath} alt="" loading="lazy"/><span className="tag">{r.category}</span><span className="article-version">{r.version}</span></div><div className="report-body"><span className="eyebrow">{new Date(r.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><h3>{r.title}</h3><p>{r.summary}</p><span className="text-link">Read the report<ArrowUpRight size={15}/></span></div></Link>)}</div><div className="small muted news-note"><ShieldCheck size={14}/>Source-linked reports. New research is published only after its checks pass.</div>
 <SectionTitle title="A little knowledge goes a long way" to="guides" label="Explore guides"/><div className="guide-list">{GUIDES.slice(0,3).map((g,i)=><Link to={'guides/'+g.id} className="guide-row" key={g.id}><span className="guide-number">0{i+1}</span><div><span className="eyebrow">{g.category}</span><h3>{g.title}</h3></div><span className="read-time"><Clock size={13}/>{g.minutes} min</span><ArrowUpRight size={17}/></Link>)}</div></div>
 <aside className="home-aside"><section className="case-card"><div className="section-title"><span className="eyebrow">YOUR CURRENT INVESTIGATION</span><NotebookPen size={18}/></div><h3>{MAPS.find(m=>m.id===session.map)?.name??'New investigation'}</h3><p className="small muted">{session.evidenceCount} evidence / Saved on this device</p><div className="case-stats"><div><strong>{String(found.length).padStart(2,'0')}</strong><span>evidence found</span></div><div><strong>{String(active.length).padStart(2,'0')}</strong><span>ghosts remain</span></div></div>{found.length>0?<EvidenceTags evidence={found.map(e=>e.id)}/>:<p className="case-empty">A clean page. A new mystery.<br/>Start with what you know.</p>}<Link to="evidence" className="button primary full">{found.length?'Continue investigation':'Open evidence book'}<ArrowRight size={17}/></Link></section><Link to="guides/mimic" className="field-note"><div className="note-pin"/><span className="eyebrow">PINNED FIELD NOTE / 001</span><h3>Orbs do not always<br/>tell the whole story.</h3><p>The Mimic keeps its extra orbs, even when the contract gives no evidence.</p><span className="text-link">Learn the exception<ArrowUpRight size={15}/></span><div className="note-sketch"><Ghost size={48} strokeWidth={1}/></div></Link><Link to="community" className="community-teaser"><div className="icon-box"><Compass size={21}/></div><h3>Better together.</h3><p>Find useful discussions, player research, and places to compare notes.</p><span className="text-link">Explore the community<ArrowRight size={15}/></span></Link></aside></div></>;
}
