import {useChapterState} from './chapterState';
import {replaceCase} from './Workspace';
import { useEffect,useMemo,useState } from 'react';
import { ArrowRight,BookOpen,Check,CheckCheck,Copy,Filter,Ghost,MessageSquare,Plus,RotateCcw,Search,Send,ShieldCheck,Sparkles,Undo2,X } from 'lucide-react';
import { EVIDENCE,OBSERVATIONS,freshSession,type Evidence,type Session } from './model';
import { applySuggestions,nextTest,parseObservations,type ParsedObservation } from './engine';
import { Link,route,useHub } from './context';
import { Empty,EvidenceTags,GhostCard,Notice,PageHeading,SourceLink,evidenceIcons } from './ui';
import { MAPS } from './content';

export function EvidenceBook(){
  const {session,setSession,candidates,undo,canUndo,notice}=useHub();
  const [query,setQuery]=useChapterState('EvidenceBook-query',''),[category,setCategory]=useChapterState('EvidenceBook-category','All'),[showRuled,setShowRuled]=useChapterState('EvidenceBook-showRuled',false),[expanded,setExpanded]=useChapterState('EvidenceBook-expanded',true);
  const active=candidates.filter(c=>!c.eliminated),next=nextTest(candidates,session);
  const visible=OBSERVATIONS.filter(o=>(category==='All'||o.category===category)&&`${o.label} ${o.aliases.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const cycle=(id:Evidence)=>{const current=session.evidence[id]??'unknown';setSession({...session,evidence:{...session.evidence,[id]:current==='unknown'?'found':current==='found'?'ruled-out':'unknown'}});};
  const toggle=(id:string)=>setSession({...session,observations:session.observations.includes(id)?session.observations.filter(x=>x!==id):[...session.observations,id]});
  async function copy(){try{await navigator.clipboard.writeText(`Ghost Hub | ${session.evidenceCount} evidence\nFound: ${EVIDENCE.filter(e=>session.evidence[e.id]==='found').map(e=>e.name).join(', ')||'None'}\nCandidates: ${active.map(c=>c.ghost.name).join(', ')||'No match'}\nNext: ${next.title}`);notice('Candidate list copied.');}catch{notice('Clipboard access was blocked by your browser.');}}
  return <><PageHeading eyebrow="INVESTIGATE / FIELD WORKSPACE" title="Evidence book" description="Follow the evidence. Question the behaviour. Find your ghost." action={<button className="button" disabled={!canUndo} onClick={undo}><Undo2 size={16}/>Undo</button>}/><div className="investigation-bar"><label>Evidence available<select aria-label="Evidence available" value={session.evidenceCount} onChange={e=>setSession({...session,evidenceCount:Number(e.target.value) as Session['evidenceCount']})}><option value={3}>3 / Standard</option><option value={2}>2 / Nightmare</option><option value={1}>1 / Insanity</option><option value={0}>0 / Custom</option></select></label><label>Location<select aria-label="Investigation map" value={session.map} onChange={e=>setSession({...session,map:e.target.value})}>{MAPS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="bar-end"><span className="small muted">Saved on this device</span><button className="text-button" onClick={()=>{if(confirm('Start a fresh investigation? Your saved journal entries will remain.'))replaceCase(freshSession(),setSession);}}><RotateCcw size={15}/>Reset</button></div></div>
  <div className="evidence-layout"><aside className="filter-stack"><section className="panel"><div className="section-title"><h2>Evidence</h2><span className="small muted">Click to cycle</span></div><div className="evidence-legend"><span><Check size={12}/>Found</span><span><X size={12}/>Ruled out</span><span>Unknown</span></div><div className="evidence-controls">{EVIDENCE.map(e=>{const Icon=evidenceIcons[e.id],state=session.evidence[e.id]??'unknown';return <button key={e.id} className={`evidence-control ${state}`} onClick={()=>cycle(e.id)} aria-label={`${e.name}: ${state}. Click to change.`} title={e.hint}><Icon size={19}/><span>{e.name}</span><span className="evidence-mark">{state==='found'?<Check size={15}/>:state==='ruled-out'?<X size={15}/>:<Plus size={14}/>}</span></button>;})}</div>{session.evidenceCount<3&&<p className="small muted">Hidden evidence cannot be obtained. Only mark a negative when your test really rules it out.</p>}</section>
  <section className="panel behaviour-panel"><button className="section-toggle" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><h2>Behaviour & telltales</h2><Filter size={17}/></button>{expanded&&<><p className="small muted">Something felt unusual? Add what you saw.</p><div className="input-icon"><Search size={16}/><input aria-label="Search behaviours" placeholder="Salt, lights, footsteps..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="chip-row compact">{['All','Electricity','Interactions','Hunts','Evidence behaviour'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)} className={`chip ${category===c?'selected':''}`}>{c}</button>)}</div><div className="behaviour-list">{visible.map(o=><button key={o.id} aria-pressed={session.observations.includes(o.id)} className={session.observations.includes(o.id)?'selected':''} onClick={()=>toggle(o.id)}><span>{o.label}<small>{o.kind==='diagnostic'?'Conditional rule-out':o.kind==='ambiguous'?'Needs context':'Supporting clue'}</small></span>{session.observations.includes(o.id)?<Check size={15}/>:<Plus size={15}/>}</button>)}</div>{!visible.length&&<p className="muted small">No matching observation. Describe it to the Detective.</p>}<Link className="text-link" to="detective">Describe it in your own words<ArrowRight size={15}/></Link></>}</section></aside>
  <div className="candidate-area"><div className="next-test"><div className="icon-box"><ShieldCheck size={22}/></div><div><span className="eyebrow">YOUR NEXT MOVE</span><h3>{next.title}</h3><p>{next.detail}</p></div></div>{session.observations.length>0&&<div className="observation-notes">{OBSERVATIONS.filter(o=>session.observations.includes(o.id)).map(o=><Notice key={o.id}><strong>{o.label}.</strong> {o.detail} {o.question}</Notice>)}</div>}<div className="section-title candidates-title"><h2>{active.length}<span> possible ghosts</span></h2><button className="text-button" onClick={copy}><Copy size={15}/>Copy list</button></div><label className="checkbox-label"><input type="checkbox" checked={showRuled} onChange={e=>setShowRuled(e.target.checked)}/>Show ruled-out ghosts ({candidates.length-active.length})</label><div className="ghost-grid">{candidates.filter(c=>showRuled||!c.eliminated).map(c=><GhostCard key={c.ghost.id} candidate={c}/>)}</div>{!active.length&&!showRuled&&<Empty title="The clues do not agree yet" icon={Ghost}>Review the most recent result or your evidence-count setting. An unobserved result is often still unknown.</Empty>}</div></div></>;
}

export {Detective} from './Detective';
