import {useChapterState} from './chapterState';
import { useState } from 'react';
import { ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,Clock,Layers,MapPin,Plus,Search,ShieldCheck,Trash2 } from 'lucide-react';
import { Link,useHub } from './context';
import { EQUIPMENT,GUIDES,MAPS } from './content';
import { Empty,Notice,PageHeading,SourceLink,icons } from './ui';
import { readValue,writeValue } from './storage';
import { z } from 'zod';

export {GhostLibrary} from './GhostEncyclopedia';
export function Equipment({id}:{id?:string}){
 const [query,setQuery]=useChapterState('Equipment-query',''),[category,setCategory]=useChapterState('Equipment-category','All');const item=EQUIPMENT.find(e=>e.id===id);
 if(id&&!item)return <Empty title="Equipment not found">Return to the equipment library.</Empty>;
 if(item){const Icon=icons[item.icon as keyof typeof icons];return <><Link to="equipment" className="back-link"><ArrowLeft size={15}/>Equipment library</Link><PageHeading eyebrow={'EQUIPMENT / '+item.category.toUpperCase()} title={item.name} description={item.summary} action={<div className="equipment-emblem"><Icon size={56} strokeWidth={1}/></div>}/><div className="two-columns"><section className="panel prose"><h2>In the field</h2><ol>{item.steps.map(s=><li key={s}>{s}</li>)}</ol><Notice>{item.caution}</Notice><Link to="evidence" className="button primary">Use in your investigation<ArrowRight size={16}/></Link></section><section className="panel"><h2>Tier overview</h2>{item.tiers.map((t,i)=><div className="tier-row" key={t}><span className="tier-number">{['I','II','III'][i]}</span><p>{t}</p></div>)}<p className="small muted">A practical overview. Consult the reference for exact ranges and current upgrade values.</p><SourceLink url={'https://phasmophobia.fandom.com/wiki/'+item.wiki}/></section></div></>;}
 const matching=EQUIPMENT.filter(e=>(category==='All'||e.category===category)&&(e.name+' '+e.summary).toLowerCase().includes(query.toLowerCase()));
 return <><PageHeading eyebrow="EXPLORE / KNOW YOUR KIT" title="Equipment library" description="The right tool is only useful when you know what its result means."/><div className="search-toolbar"><div className="input-icon"><Search size={17}/><input placeholder="Search equipment..." aria-label="Search equipment" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="chip-row">{['All','Evidence','Protection','Tracking','Utility','Media'].map(c=><button className={'chip '+(category===c?'selected':'')} aria-pressed={category===c} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div><div className="equipment-grid">{matching.map(e=>{const Icon=icons[e.icon as keyof typeof icons];return <Link to={'equipment/'+e.id} className="equipment-card" key={e.id}><div className="equipment-visual"><Icon size={62} strokeWidth={1}/><span className="equipment-tier">I / II / III</span></div><div className="equipment-content"><span className="eyebrow">{e.category}</span><h3>{e.name}<ArrowUpRight size={16}/></h3><p>{e.summary}</p></div></Link>;})}</div>{!matching.length&&<Empty title="No equipment found">Try a different term or category.</Empty>}</>;
}
export function Guides({id}:{id?:string}){
 const [query,setQuery]=useChapterState('Guides-query','');const guide=GUIDES.find(g=>g.id===id);
 if(id&&!guide)return <Empty title="Guide not found">Choose a guide from the library.</Empty>;
 if(guide)return <><Link to="guides" className="back-link"><ArrowLeft size={15}/>Guides & mechanics</Link><article className="article-page"><PageHeading eyebrow={guide.category.toUpperCase()+' / '+guide.minutes+' MIN READ'} title={guide.title} description={guide.summary}/><div className="article-content prose">{guide.sections.map(([title,body],i)=><section key={title}><span className="article-section-number">0{i+1}</span><h2>{title}</h2><p>{body}</p></section>)}<div className="article-source"><ShieldCheck size={19}/><div><strong>Keep the reference in view</strong><p>Game updates can change mechanics. This guide is a practical introduction, not a substitute for checking the current source.</p><SourceLink url={guide.source}/></div></div><Link className="button primary" to="evidence">Put it into practice<ArrowRight size={16}/></Link></div></article></>;
 return <><PageHeading eyebrow="EXPLORE / FIELD KNOWLEDGE" title="Guides & mechanics" description="Short answers when the ghost is waiting. Deeper explanations when it is not."/><div className="input-icon library-search"><Search size={17}/><input aria-label="Search guides" placeholder="Search evidence, hunts, sanity..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="guide-card-grid">{GUIDES.filter(g=>(g.title+' '+g.category+' '+g.summary).toLowerCase().includes(query.toLowerCase())).map((g,i)=><Link to={'guides/'+g.id} className="guide-card" key={g.id}><div className="guide-card-header"><span className="eyebrow">{g.category}</span><BookOpen size={21}/></div><span className="guide-index">{String(i+1).padStart(2,'0')}</span><h2>{g.title}</h2><p>{g.summary}</p><div className="guide-card-footer"><span><Clock size={14}/>{g.minutes} min read</span><ArrowUpRight size={18}/></div></Link>)}</div></>;
}
const MarkerSchema=z.object({id:z.string(),map:z.string(),floor:z.string(),label:z.string().max(60),x:z.number().min(0).max(100),y:z.number().min(0).max(100)});
export function Maps(){
 const {session,setSession,notice}=useHub();const [selected,setSelected]=useChapterState('Maps-selected',session.map),[floor,setFloor]=useChapterState('Maps-floor',''),[query,setQuery]=useChapterState('Maps-query',''),[markerLabel,setMarkerLabel]=useChapterState('Maps-markerLabel','Ghost room');
 const [markers,setMarkers]=useState(()=>readValue('map-markers',z.array(MarkerSchema).max(300),[]));const map=MAPS.find(m=>m.id===selected)??MAPS[0];const currentFloor=map.floors.includes(floor)?floor:map.floors[0];
 const current=markers.filter(m=>m.map===map.id&&m.floor===currentFloor);
 const update=(next:typeof markers)=>{setMarkers(next);if(!writeValue('map-markers',next))notice('Map markers could not be saved on this device.');};
 const add=(e:React.MouseEvent<HTMLDivElement>)=>{if(!markerLabel.trim()||markers.length>=300)return;const r=e.currentTarget.getBoundingClientRect();update([...markers,{id:crypto.randomUUID(),map:map.id,floor:currentFloor,label:markerLabel.trim(),x:Math.max(2,Math.min(98,(e.clientX-r.left)/r.width*100)),y:Math.max(4,Math.min(96,(e.clientY-r.top)/r.height*100))}]);};
 return <><PageHeading eyebrow="EXPLORE / KNOW THE LOCATION" title="Map atlas" description="Choose a contract. Keep your bearings. Record the places that matter."/><div className="maps-layout"><aside className="panel map-list"><div className="input-icon"><Search size={16}/><input aria-label="Search maps" placeholder="Find a location..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{MAPS.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())).map(m=><button key={m.id} className={selected===m.id?'selected':''} onClick={()=>{setSelected(m.id);setFloor('');}}><MapPin size={17}/><span>{m.name}<small>{m.type} / {m.setting}</small></span><ArrowRight size={15}/></button>)}</aside><div><div className="map-title"><div><span className="eyebrow">{map.type.toUpperCase()} / {map.setting.toUpperCase()}</span><h2>{map.name}</h2></div><button className="button" onClick={()=>{setSession({...session,map:map.id});notice('Location added to your investigation.');}}>Set as current map<Check size={15}/></button></div><div className="chip-row floor-tabs">{map.floors.map(f=><button key={f} aria-pressed={currentFloor===f} className={'chip '+(currentFloor===f?'selected':'')} onClick={()=>setFloor(f)}><Layers size={14}/>{f}</button>)}</div><Notice>This is a personal planning board, not a verified floor plan. Use the current map reference for actual room layouts and spawn locations.</Notice><div className="planning-board" onClick={add}><div className="board-axis">N <span>+</span></div><div className="board-watermark"><MapPin size={44} strokeWidth={1}/><h3>{map.name}</h3><p>{currentFloor} / personal planning board</p><span>Click to place a labelled marker</span></div>{current.map(m=><div className="map-marker" key={m.id} style={{left:m.x+'%',top:m.y+'%'}}><MapPin size={21}/><span>{m.label}</span></div>)}</div><div className="marker-form"><label>Marker label<input value={markerLabel} maxLength={60} onChange={e=>setMarkerLabel(e.target.value)}/></label><button className="button" disabled={!markerLabel.trim()} onClick={()=>update([...markers,{id:crypto.randomUUID(),map:map.id,floor:currentFloor,label:markerLabel.trim(),x:50,y:50}])}><Plus size={15}/>Add to centre</button></div>{current.length>0&&<div className="marker-list">{current.map(m=><div key={m.id}><MapPin size={14}/><span>{m.label}</span><button className="icon-button" aria-label={'Remove marker '+m.label} onClick={()=>update(markers.filter(v=>v.id!==m.id))}><Trash2 size={15}/></button></div>)}</div>}<section className="panel prose"><h3>Field orientation</h3><p>{map.tip}</p><SourceLink url={'https://phasmophobia.fandom.com/wiki/'+map.wiki}>Open current map reference</SourceLink></section></div></div></>;
}
