export const CURSED_ITEMS=[
 {id:'haunted-mirror',name:'Haunted Mirror',tag:'Find the room',summary:'A brief view of the favourite room, bought with sanity and a dangerous breaking point.',use:'The reflection shows the favourite room. Treat it as a visual clue: furnishings and wall finishes help the team identify the location.',risk:'Watching drains sanity quickly. Reaching zero while using it can break the mirror and trigger a cursed hunt.',steps:['Agree who will watch the sanity monitor and who will identify the room.','Use a short look, then put the mirror down before discussing the view.','Check the room normally instead of repeatedly paying for the same clue.'],misread:'A room clue identifies a location, not a ghost species.',wiki:'Haunted_Mirror'},
 {id:'ouija-board',name:'Ouija Board',tag:'Ask carefully',summary:'Ask a focused question, watch your sanity, and close the conversation properly.',use:'The board responds to supported questions. A location answer describes where the ghost is, which need not be its favourite room.',risk:'An unaffordable question can break the board. Hide and seek deliberately starts a cursed-hunt sequence. Say goodbye to deactivate it.',steps:['Tell your team before activating the board.','Ask one question with a clear purpose rather than an open-ended conversation.','Finish with goodbye and confirm the board is inactive before leaving.'],misread:'The answer does not turn normal movement into evidence of a room change.',wiki:'Ouija_Board'},
 {id:'music-box',name:'Music Box',tag:'Listen, then retreat',summary:'A song can help locate the ghost. It is not a harmless audio toy.',use:'An activated box makes the ghost sing along. Near the box, the ghost may appear and approach it.',risk:'Dropping an active box or letting the approaching ghost reach it can initiate a cursed hunt.',steps:['Choose a retreat route before using the box.','Let one player handle it while the others listen from planned positions.','Use the sound as a location clue and stop chasing the spectacle.'],misread:'A scripted cursed-item appearance is not a normal ghost event for a behavioural test.',wiki:'Music_Box'},
 {id:'summoning-circle',name:'Summoning Circle',tag:'Planned manifestation',summary:'A controlled-looking appearance with a very uncontrolled ending.',use:'Lighting the circle summons the ghost for a brief manifestation before a hunt.',risk:'Do not treat the initial stillness as safety. The hunt is part of the activation, not a natural sanity-threshold test.',steps:['Agree on the purpose of the attempt before lighting candles.','Keep the escape route clear and have protection ready.','Warn every player, including anyone working elsewhere in the building.'],misread:'A hunt caused by the circle says nothing reliable about the ghost\'s normal hunt threshold.',wiki:'Summoning_Circle'},
 {id:'voodoo-doll',name:'Voodoo Doll',tag:'Force an interaction',summary:'More activity is useful only if you understand what caused it.',use:'Pushing a pin can provoke an interaction. The heart pin can trigger a cursed hunt.',risk:'You do not choose which pin is pushed. Do not use the doll as if every activation has the same risk.',steps:['Keep the investigation objective specific: locate activity or observe an interaction.','Tell your team when you use a pin so they can label the event correctly.','Stop before an optional experiment puts an unprepared teammate at risk.'],misread:'Forced activity is not proof of a naturally active ghost.',wiki:'Voodoo_Doll'},
 {id:'tarot-cards',name:'Tarot Cards',tag:'Random consequences',summary:'A random-effect item, not a dependable evidence tool.',use:'Drawing a card can produce a range of effects. The Fool can disguise itself as another card before revealing the false result.',risk:'Possible outcomes include cursed hunts and immediate death. A promising first image is not necessarily the card\'s final effect.',steps:['Get the team\'s agreement before drawing.','Watch the complete card animation and record the final result.','Do not draw simply to rescue an already confusing behavioural test.'],misread:'Card-triggered hunts or activity must not be entered as ordinary ghost behaviour.',wiki:'Tarot_Cards'},
 {id:'monkey-paw',name:'Monkey Paw',tag:'Every wish has a cost',summary:'Useful wishes carry consequences that can reshape the investigation.',use:'Supported wishes can provide help or information, but each has a drawback. The knowledge wish removes an incorrect evidence option and brings severe consequences.',risk:'The knowledge wish can cause a cursed hunt and lasting sensory penalties. Other wishes have different trade-offs; read the exact wish before using it.',steps:['Choose the exact supported wish and read its downside first.','Warn the team which part of the case may change.','Record the wish in your journal so later clues are not interpreted out of context.'],misread:'A wish-modified investigation should not be compared directly with untouched default mechanics.',wiki:'Monkey_Paw'}
];
export const KNOWN_ISSUES=[
 {id:'fsr-journal',name:'Journal readability with FSR 1.0',status:'Known issue',version:'0.19.0.1',date:'2026-09-10',summary:'The developer lists journal readability with FSR 1.0 as a known issue in this release.',impact:'Unreadable UI is not an evidence result. Try another upscaling setting while checking the current patch notes for a later fix.',source:'https://store.steampowered.com/news/externalpost/steam_community_announcements/1843481262691864'},
 {id:'knowledge-evidence',name:'Monkey Paw knowledge crossed out the wrong evidence',status:'Reported fixed',version:'0.19.0.1',date:'2026-09-10',summary:'The patch addresses the knowledge wish incorrectly crossing out the correct evidence.',impact:'If your case relies on a knowledge wish made before this fix, do not use that old result to establish a ghost rule.',source:'https://store.steampowered.com/news/externalpost/steam_community_announcements/1843481262691864'},
 {id:'uv-media',name:'UV fingerprints failed to charge for media',status:'Reported fixed',version:'0.19.0.1',date:'2026-09-10',summary:'The developer reports a fix for affected fingerprint surfaces on Willow Street and Nell\'s Diner.',impact:'A failed photo or charging interaction is not the same as confirming that UV evidence is absent.',source:'https://store.steampowered.com/news/externalpost/steam_community_announcements/1843481262691864'},
 {id:'video-black-screen',name:'Video camera black-screen problems',status:'Reported fixed',version:'0.19.0.1',date:'2026-09-10',summary:'Several video camera black-screen cases are addressed in the patch.',impact:'A camera that is not displaying the scene cannot establish the absence of Ghost Orbs or camera-only D.O.T.S.',source:'https://store.steampowered.com/news/externalpost/steam_community_announcements/1843481262691864'},
 {id:'door-audio-delay',name:'Delayed door-closing audio',status:'Reported fixed',version:'0.19.0.0',date:'2026-08-25',summary:'The Quality of Life Part 2 notes include a fix for delayed door-closing sounds.',impact:'Do not identify a Yurei from an audio timing anomaly alone. Check the physical door interaction and the conditions of the test.',source:'https://kineticgames.co.uk/news/phasmophobia-v01900-quality-of-life-part-2'}
];
