import { useState } from 'react';
import { ArrowLeft,ArrowUpRight,Flame,Search } from 'lucide-react';
import { Link } from './context';
import { CURSED_ITEMS,KNOWN_ISSUES } from './reference';
import { Empty,Notice,PageHeading,SourceLink } from './ui';
export function CursedPossessions({id}:{id?:string}){
 const [q,setQ]=useState('');const item=CURSED_ITEMS.find(x=>x.id===id);
 if(id&&!item)return <Empty title="Unknown cursed possession">Choose an item from the cursed possessions library.</Empty>;
 if(item)return <><Link to="cursed" className="back-link"><ArrowLeft size={15}/>Cursed possessions</Link><PageHeading eyebrow={'CURSED POSSESSIONS / '+item.tag.toUpperCase()} title={item.name} description={item.summary}/><div className="two-columns"><section className="panel prose"><h2>What it does</h2><p>{item.use}</p><h3>The price</h3><Notice>{item.risk}</Notice><h3>Do not misread the result</h3><p>{item.misread}</p></section><section className="panel prose"><h2>Before you touch it</h2><ol>{item.steps.map(s=><li key={s}>{s}</li>)}</ol><SourceLink url={'https://phasmophobia.fandom.com/wiki/'+item.wiki}>Read the detailed community reference</SourceLink><p className="small muted">A field-use overview, not an exhaustive wish, question, card or probability table. Verify exact costs against your current game version.</p><Link className="button" to="journal">Record the activation</Link></section></div></>;
 const items=CURSED_ITEMS.filter(x=>(x.name+' '+x.summary+' '+x.tag).toLowerCase().includes(q.toLowerCase()));
 return <><PageHeading eyebrow="FIELD KNOWLEDGE / A DANGEROUS BARGAIN" title="Some clues come at a cost." description="Seven cursed possessions. What they reveal, what they risk, and how they can contaminate an otherwise good test."/><Notice>A cursed-item hunt is not a normal hunt-threshold observation. Tell the team when you activate an item and keep that event separate from natural behaviour.</Notice><div className="search-toolbar"><div className="input-icon"><Search size={18}/><input aria-label="Search cursed possessions" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search an item or purpose..."/></div></div><div className="cursed-grid">{items.map((x,i)=><Link className="panel cursed-card" to={'cursed/'+x.id} key={x.id}><div className="cursed-card-top"><Flame size={32} strokeWidth={1}/><span className="eyebrow">OBJECT / 0{i+1}</span></div><span className="tag amber">{x.tag}</span><h2>{x.name}<ArrowUpRight size={18}/></h2><p>{x.summary}</p><span className="text-link">Understand the trade-off</span></Link>)}</div>{!items.length&&<Empty title="No matching object">Try the item's name.</Empty>}</>;
}
export function KnownBugs(){
 const [filter,setFilter]=useState('All');return <><PageHeading eyebrow="RESEARCH DESK / DON'T CHASE A BUG" title="A glitch is not a ghost tell." description="Developer-reported problems that can confuse an investigation, with their stated fix version kept visible."/><Notice>This is a source-checked snapshot through 0.19.0.1, not a live exhaustive bug tracker. "Reported fixed" means the developer says it was fixed; Ghost Hub has not independently reproduced the fix. <Link to="updates">Check newer reports</Link>.</Notice><div className="chip-row archive-tabs">{['All','Known issue','Reported fixed'].map(s=><button className={'chip '+(filter===s?'selected':'')} key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}</button>)}</div><div className="issue-list">{KNOWN_ISSUES.filter(x=>filter==='All'||x.status===filter).map(x=><article className="panel prose issue-card" key={x.id}><div className="button-row"><span className={'tag '+(x.status==='Known issue'?'amber':'')}>{x.status}</span><span className="small muted">{x.version} / {x.date}</span></div><h2>{x.name}</h2><p>{x.summary}</p><h3>What it means for your case</h3><p>{x.impact}</p><SourceLink url={x.source}>Developer patch notes</SourceLink></article>)}</div><section className="panel prose"><h2>Found something that doesn't fit?</h2><p>Record the game version, difficulty, map, equipment tier and exact sequence. Keep a repeatable test separate from a theory. Community reports never rewrite the evidence engine automatically.</p><Link className="button" to="submit">Submit a finding</Link></section></>;
}
