import { useEffect,useRef,useState } from 'react';
import { z } from 'zod';
import { Check,Download,FileUp,NotebookPen,Pause,Play,Plus,RotateCcw,Save,Timer,Trash2,Volume2 } from 'lucide-react';
import { Link,useHub } from './context';
import { EVIDENCE,SessionSchema,SnapshotSchema,type Snapshot } from './model';
import { downloadJson,readValue,writeValue } from './storage';
import { Empty,EvidenceTags,Notice,PageHeading,SectionTitle } from './ui';
import { MAPS } from './content';

const TimerSchema=z.object({duration:z.number().int().min(1).max(3600),remaining:z.number().min(0).max(3600),endsAt:z.number().nullable(),finished:z.boolean()});
export function ToolsPage(){
 const {sound,notice}=useHub();const [timer,setTimer]=useState(()=>readValue('timer',TimerSchema,{duration:90,remaining:90,endsAt:null,finished:false}));const [custom,setCustom]=useState(90),[now,setNow]=useState(Date.now()),[taps,setTaps]=useState<number[]>([]),[checks,setChecks]=useState(()=>readValue('checklist',z.array(z.string()),[]));
 const audioRef=useRef<AudioContext|null>(null);const left=timer.endsAt?Math.max(0,Math.ceil((timer.endsAt-now)/1000)):timer.remaining;
 useEffect(()=>{writeValue('timer',timer);},[timer]);
 useEffect(()=>{if(!timer.endsAt)return;const tick=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(tick);},[timer.endsAt]);
 useEffect(()=>{if(timer.endsAt&&left===0){setTimer(t=>({...t,endsAt:null,remaining:0,finished:true}));notice('Timer complete.');if(sound&&audioRef.current){const ctx=audioRef.current;for(let i=0;i<3;i++){const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.connect(gain);gain.connect(ctx.destination);oscillator.frequency.value=660;gain.gain.setValueAtTime(.12,ctx.currentTime+i*.25);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.25+.16);oscillator.start(ctx.currentTime+i*.25);oscillator.stop(ctx.currentTime+i*.25+.18);}}}},[left,timer.endsAt,sound,notice]);
 useEffect(()=>()=>{void audioRef.current?.close();},[]);
 const setDuration=(seconds:number)=>{setTimer({duration:seconds,remaining:seconds,endsAt:null,finished:false});setCustom(seconds);};
 const start=()=>{if(sound){audioRef.current??=new AudioContext();void audioRef.current.resume();}const remaining=left||timer.duration;setNow(Date.now());setTimer({...timer,remaining,endsAt:Date.now()+remaining*1000,finished:false});};
 const tap=()=>{const time=performance.now();setTaps(v=>v.length&&time-v[v.length-1]>4000?[time]:[...v.slice(-15),time]);};
 const bpm=taps.length>2?Math.round((taps.length-1)*60000/(taps[taps.length-1]-taps[0])):null;
 const checklist=['Confirm the contract settings','Locate activity and verify the room','Place passive evidence equipment','Check an escape route','Record confirmed evidence','Choose a distinguishing test'];
 return <><PageHeading eyebrow="INVESTIGATE / IN YOUR TOOLKIT" title="Field tools" description="Keep track of the seconds. Keep your head in the investigation."/><div className="two-columns"><section className={'panel timer-panel '+(timer.finished?'timer-finished':'')}><div className="section-title"><h2><Timer size={20}/>Investigation timer</h2><span className="tag">{timer.endsAt?'Running':timer.finished?'Complete':'Ready'}</span></div><div className="timer-display" role="timer" aria-label={`${left} seconds remaining`}>{String(Math.floor(left/60)).padStart(2,'0')}<span>:</span>{String(left%60).padStart(2,'0')}</div><div className="timer-progress"><span style={{width:Math.min(100,left/timer.duration*100)+'%'}}/></div><div className="timer-actions"><button className="button primary" onClick={timer.endsAt?()=>setTimer({...timer,endsAt:null,remaining:left}):start}>{timer.endsAt?<Pause size={18}/>:<Play size={18}/>} {timer.endsAt?'Pause':'Start'}</button><button className="button" aria-label="Reset timer" onClick={()=>setDuration(timer.duration)}><RotateCcw size={18}/></button></div><div className="chip-row timer-presets">{[60,90,180].map(v=><button key={v} className={'chip '+(timer.duration===v?'selected':'')} onClick={()=>setDuration(v)}>{v} seconds</button>)}</div><form className="inline-form" onSubmit={e=>{e.preventDefault();if(Number.isInteger(custom)&&custom>0&&custom<=3600)setDuration(custom);}}><label>Custom seconds<input aria-label="Custom timer seconds" type="number" min={1} max={3600} value={custom} onChange={e=>setCustom(Number(e.target.value))}/></label><button className="button">Set timer</button></form><p className="small muted">The end time is saved through navigation and refresh. Audible alerts require this page to be open and browser audio to be enabled.</p><SourceTimerNote/></section><section className="panel tap-panel"><span className="eyebrow">FOOTSTEP RHYTHM</span><h2>Listen. Tap. Compare.</h2><p>Tap along with the footsteps. A rhythm measurement is a clue, not a ghost identification.</p><div className="bpm-display">{bpm??'--'}<span>BPM / {taps.length} taps</span></div><button className="tap-button" onClick={tap}>TAP<small>in time with each footstep</small></button><button className="text-button" onClick={()=>setTaps([])}><RotateCcw size={15}/>Reset rhythm</button><Notice>No automatic metres-per-second conversion: speed modifiers, acceleration and calibration can change the interpretation.</Notice></section></div><section className="panel checklist"><SectionTitle title="Contract checklist"/>{checklist.map(c=><label key={c}><input type="checkbox" checked={checks.includes(c)} onChange={()=>{const next=checks.includes(c)?checks.filter(v=>v!==c):[...checks,c];setChecks(next);writeValue('checklist',next);}}/>{c}</label>)}</section></>;
}
function SourceTimerNote(){return <Link className="text-link" to="equipment/incense">Understand incense timing</Link>;}
export function Journal(){
 const {session,setSession,snapshots,setSnapshots,catalog,notice}=useHub();const [result,setResult]=useState('Unresolved');const importRef=useRef<HTMLInputElement>(null);
 const save=()=>{if(snapshots.length>=100){notice('Journal limit reached. Export and remove older entries first.');return;}setSnapshots([{id:crypto.randomUUID(),date:new Date().toISOString(),session:structuredClone(session),result},...snapshots]);notice('Investigation saved to your journal.');};
 const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>2_000_000)throw Error('Journal file is too large.');const raw=JSON.parse(await file.text());const parsed=z.object({format:z.literal('ghost-hub-journal-v1'),snapshots:z.array(SnapshotSchema).max(100)}).parse(raw);if(snapshots.length&& !confirm('Replace this device\'s saved journal with the imported entries?'))return;setSnapshots(parsed.snapshots);notice('Journal imported.');}catch(err){notice(err instanceof Error?err.message:'Invalid journal file.');}if(importRef.current)importRef.current.value='';};
 return <><PageHeading eyebrow="INVESTIGATE / KEEP A RECORD" title="Field journal" description="Save the clues, the wrong turns, and the moment it all made sense." action={<div className="button-row"><button className="button" onClick={()=>downloadJson('ghost-hub-journal.json',{format:'ghost-hub-journal-v1',snapshots})}><Download size={16}/>Export</button><button className="button" onClick={()=>importRef.current?.click()}><FileUp size={16}/>Import</button><input hidden ref={importRef} type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/></div>}/><div className="two-columns"><section className="panel journal-editor"><span className="eyebrow">CURRENT CASE</span><label>Investigation name<input value={session.name} maxLength={80} onChange={e=>setSession({...session,name:e.target.value})}/></label><label>Field notes<textarea rows={8} value={session.notes} maxLength={12000} placeholder="What happened? What did you test? What changed?" onChange={e=>setSession({...session,notes:e.target.value})}/></label><div className="two-fields"><label>Team sanity (manual)<input type="number" min={0} max={100} value={session.sanity} onChange={e=>setSession({...session,sanity:Math.max(0,Math.min(100,Number(e.target.value)))})}/></label><label>Final result<select aria-label="Final ghost result" value={result} onChange={e=>setResult(e.target.value)}><option>Unresolved</option>{catalog.ghosts.map(g=><option key={g.id}>{g.name}</option>)}</select></label></div><button className="button primary" onClick={save}><Save size={16}/>Save investigation</button><p className="small muted">Draft changes save automatically. Saved investigations are snapshots on this device; export them for backup or another device.</p></section><section><SectionTitle title={`Saved investigations (${snapshots.length})`}/>{!snapshots.length?<Empty title="Your first case starts here" icon={NotebookPen}>Save an investigation to preserve its evidence, observations, notes and final result.</Empty>:<div className="journal-list">{snapshots.map(s=><article className="panel" key={s.id}><div className="section-title"><span className="eyebrow">{new Date(s.date).toLocaleDateString()}</span><button className="icon-button" aria-label={'Delete '+s.session.name} onClick={()=>{if(confirm('Delete this saved investigation?'))setSnapshots(snapshots.filter(v=>v.id!==s.id));}}><Trash2 size={16}/></button></div><h3>{s.session.name||'Untitled investigation'}</h3><p className="small muted">{MAPS.find(m=>m.id===s.session.map)?.name??s.session.map} / {s.result}</p><EvidenceTags evidence={EVIDENCE.filter(e=>s.session.evidence[e.id]==='found').map(e=>e.id)}/><p className="journal-preview">{s.session.notes||'No additional notes.'}</p><button className="button" onClick={()=>{if(confirm('Restore this snapshot over the current investigation?')){setSession(s.session);notice('Investigation restored.');}}}>Restore investigation</button></article>)}</div>}</section></div></>;
}
