import { Component,type ReactNode } from 'react';
import { Activity,ArrowUpRight,BookOpen,Camera,Check,ChevronRight,Cross,Ear,Fingerprint,Flame,Footprints,Ghost as GhostIcon,Info,Radio,Radar,Scan,Search,Shield,Skull,Snowflake,Sparkles,Thermometer,Zap } from 'lucide-react';
import { EVIDENCE,type Candidate,type Evidence } from './model';
import { Link,useHub } from './context';
export const icons={activity:Activity,radio:Radio,fingerprint:Fingerprint,thermometer:Thermometer,scan:Scan,book:BookOpen,camera:Camera,flame:Flame,cross:Cross,footprints:Footprints,ear:Ear,radar:Radar};
export const evidenceIcons:Record<Evidence,typeof Activity>={emf:Activity,dots:Scan,uv:Fingerprint,freezing:Snowflake,orbs:Sparkles,writing:BookOpen,box:Radio};
export function Eyebrow({children}:{children:ReactNode}){return <div className="eyebrow">{children}</div>;}
export function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){return <div className="page-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function SectionTitle({title,to,label='View all'}:{title:string;to?:string;label?:string}){return <div className="section-title"><h2>{title}</h2>{to&&<Link to={to}>{label}<ArrowUpRight size={15}/></Link>}</div>;}
export function Empty({title,children,icon:Icon=Search}:{title:string;children:ReactNode;icon?:typeof Search}){return <div className="empty"><Icon size={32}/><h3>{title}</h3><p>{children}</p></div>;}
export function Notice({children}:{children:ReactNode}){return <div className="inline-notice"><Info size={17}/><div>{children}</div></div>;}
export function SourceLink({url,children='Read the reference'}:{url:string;children?:ReactNode}){return <a className="source-link" href={url} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14}/></a>;}
export function EvidenceTags({evidence}:{evidence:Evidence[]}){return <div className="evidence-tags">{evidence.map(e=>{const Icon=evidenceIcons[e];return <span key={e}><Icon size={13}/>{EVIDENCE.find(x=>x.id===e)?.short}</span>;})}</div>;}
export function GhostCard({candidate,compact=false}:{candidate:Candidate;compact?:boolean}){
  const {session}=useHub();const g=candidate.ghost;
  return <article className={`ghost-card ${candidate.eliminated?'eliminated':''}`}><div className="ghost-card-top"><div className="ghost-sigil"><GhostIcon size={23}/></div><span className={`tag ${candidate.support.length?'amber':''}`}>{candidate.eliminated?'Ruled out':candidate.support.length?'Worth a closer look':'Possible'}</span></div><Link to={'ghosts/'+g.id} className="ghost-name"><h3>{g.name}</h3><ArrowUpRight size={18}/></Link><EvidenceTags evidence={g.evidence}/>{!compact&&<><p>{g.summary}</p>{candidate.support.length>0&&<div className="support-line"><Zap size={13}/>{candidate.support.join(' / ')}</div>}<details><summary>Why this ghost?<ChevronRight size={15}/></summary><ul>{(candidate.reasons.length?candidate.reasons:['No confirmed results currently exclude this ghost.']).map(r=><li key={r}>{r}</li>)}</ul><strong>Next test</strong><p>{g.test}</p><p className="muted">{g.caution}</p>{g.sources.map(s=><SourceLink key={s} url={s}/>)}</details></>}{compact&&<span className="small muted">{session.evidenceCount} evidence contract</span>}</article>;
}
export class ErrorBoundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true};}render(){return this.state.error?<div className="empty"><Shield size={34}/><h2>This page could not open</h2><p>Your saved investigation remains on this device. Reload to try again.</p><button className="button primary" onClick={()=>location.reload()}>Reload Ghost Hub</button></div>:this.props.children;}}
