import { useState } from 'react';
import { ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,FileText,Ghost,Search,ShieldCheck } from 'lucide-react';
import { Link,imagePath,route,useHub } from './context';
import { EQUIPMENT,GUIDES,MAPS,RESOURCES } from './content';
import { OBSERVATIONS } from './model';
import { CURSED_ITEMS,KNOWN_ISSUES } from './reference';
import { searchRecords } from './search';
import { Empty,Notice,PageHeading,SourceLink } from './ui';
export function Updates({id}:{id?:string}){
 const {news}=useHub();const [category,setCategory]=useState('All');const report=news.reports.find(r=>r.id===id);
 if(id&&!report)return <Empty title="Report not found">Open the update archive to browse available reports.</Empty>;
 if(report)return <><Link to="updates" className="back-link"><ArrowLeft size={15}/>Research desk</Link><article className="article-page"><PageHeading eyebrow={report.category.toUpperCase()+' / '+report.date} title={report.title} description={report.summary}/><div className="article-meta"><span className="tag amber">{report.version}</span><span className="small muted">{report.status}</span></div><div className="article-banner"><img src={imagePath} alt="Original atmospheric artwork of a haunted house"/></div><div className="article-content prose">{report.body.map((p,i)=><p key={i}>{p}</p>)}<div className="article-source"><ShieldCheck size={21}/><div><h3>Read the original sources</h3>{report.sources.map(s=><SourceLink key={s.url} url={s.url}>{s.title}</SourceLink>)}<p className="small muted">Analysis is Ghost Hub's interpretation. A developer announcement and its repost do not constitute independent gameplay testing.</p></div></div><h3>Follow the trail</h3><div className="button-row">{report.related.map(r=><Link className="button" to={r} key={r}>{r.replaceAll('/',' / ')}<ArrowRight size={14}/></Link>)}</div><Link className="text-link" to="submit">Report a correction<ArrowUpRight size={15}/></Link></div></article></>;
 return <><PageHeading eyebrow="UPDATES / THE RESEARCH DESK" title="Know what changed." description="Patch notes with context. Sources you can follow. Uncertainty left visible."/><Notice>{news.lastCheckedAt?`Last successful automatic research check: ${new Date(news.lastCheckedAt).toLocaleString()}.`:'Showing the reviewed starter archive. Automatic research has not completed a scheduled run yet.'} This archive is not a guarantee that every recent patch is covered.</Notice><div className="chip-row archive-tabs">{['All',...new Set(news.reports.map(r=>r.category))].map(c=><button className={'chip '+(category===c?'selected':'')} aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="news-grid">{news.reports.filter(r=>category==='All'||r.category===category).sort((a,b)=>b.date.localeCompare(a.date)).map(r=><Link to={'updates/'+r.id} className="report-card" key={r.id}><div className="report-image"><img src={imagePath} alt="" loading="lazy"/><span className="tag">{r.category}</span><span className="article-version">{r.version}</span></div><div className="report-body"><span className="eyebrow">{r.date} / {r.status}</span><h2>{r.title}</h2><p>{r.summary}</p><span className="text-link">Read report<ArrowUpRight size={15}/></span></div></Link>)}</div></>;
}
export function GlobalSearch(){
 const {catalog,news,session,setSession,notice}=useHub();const [q,setQ]=useState(new URLSearchParams(location.hash.split('?')[1]).get('q')??'');const [type,setType]=useState('All');
 const records=[...catalog.ghosts.map(g=>({title:g.name,description:g.summary+' '+g.test,type:'Ghosts',path:'ghosts/'+g.id})),...GUIDES.map(g=>({title:g.title,description:g.summary,type:'Guides',path:'guides/'+g.id})),...EQUIPMENT.map(g=>({title:g.name,description:g.summary,type:'Equipment',path:'equipment/'+g.id})),...MAPS.map(g=>({title:g.name,description:g.setting+' '+g.tip,type:'Maps',path:'maps?map='+g.id})),...news.reports.map(g=>({title:g.title,description:g.summary,type:'Updates',path:'updates/'+g.id})),...OBSERVATIONS.map(o=>({title:o.label,description:o.detail,aliases:o.aliases,type:'Observations',path:'observation:'+o.id})),...CURSED_ITEMS.map(x=>({title:x.name,description:x.summary+' '+x.use,type:'Cursed items',path:'cursed/'+x.id})),...KNOWN_ISSUES.map(x=>({title:x.name,description:x.summary+' '+x.impact,type:'Known bugs',path:'bugs?issue='+x.id}))];
 const results=searchRecords(records,q,type);
 return <><PageHeading eyebrow="SEARCH / CONNECT THE DOTS" title="Find your next clue." description="Search ghosts, observations, equipment, maps, guides and reports."/><form className="big-search" onSubmit={e=>e.preventDefault()}><Search size={22}/><input autoFocus aria-label="Search Ghost Hub" value={q} placeholder="Try salt, freezing, a ghost name..." onChange={e=>setQ(e.target.value)}/></form><div className="chip-row archive-tabs">{['All','Ghosts','Observations','Guides','Equipment','Maps','Cursed items','Known bugs','Updates'].map(t=><button className={'chip '+(type===t?'selected':'')} aria-pressed={type===t} key={t} onClick={()=>setType(t)}>{t}</button>)}</div>{results.length?<div className="search-results">{results.map(r=><div className="search-result" key={r.path}><span className="eyebrow">{r.type}</span>{r.path.startsWith('observation:')?<><h3>{r.title}</h3><p>{r.description}</p><button className="button" onClick={()=>{const id=r.path.split(':')[1];setSession({...session,observations:[...new Set([...session.observations,id])]});notice('Observation added to your case.');}}>Add observation</button></>:<Link to={r.path}><h3>{r.title}<ArrowUpRight size={18}/></h3><p>{r.description}</p></Link>}</div>)}</div>:<Empty title={q?'No matching references yet':'What happened in your investigation?'}>{q?'Try a shorter phrase, or ask the Detective to interpret what you observed.':'Search a subject or describe a behaviour to find a useful starting point.'}</Empty>}{q&&<button className="button primary" onClick={()=>route('detective?q='+encodeURIComponent(q))}><Ghost size={17}/>Ask the Ghost Detective</button>}</>;
}
